-- drop table if exists btc_data;

create table btc_data (
    symbol varchar(10),
    rate_usd decimal,
    site_timestamp bigint,
    updated_at timestamp
);

alter table btc_data add column row_id int
generated by default as identity primary key;